# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 15:31
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deejay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dj', models.CharField(max_length=50, verbose_name='DJ Name')),
                ('pic', models.ImageField(upload_to=b'')),
                ('role', models.CharField(default='DJ', max_length=50, verbose_name='Job title')),
                ('bio', models.TextField(verbose_name='Bio')),
                ('phone', models.CharField(max_length=15, verbose_name='Phone number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Playlist date')),
                ('description', models.TextField(verbose_name='Playlist description')),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('showname', models.CharField(max_length=200, verbose_name='Show name')),
                ('showDate', models.CharField(choices=[('M', 'Monday'), ('T', 'Tuesday'), ('W', 'Wednesday'), ('TH', 'Thursday'), ('F', 'Friday'), ('SA', 'Saturday'), ('SU', 'Sunday')], max_length=50, verbose_name='Show day')),
                ('startTime', models.TimeField(verbose_name='Start time')),
                ('endTime', models.TimeField(verbose_name='End time')),
                ('description', models.TextField(verbose_name='Show description')),
                ('dj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='DJ')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albumID', models.CharField(blank=True, max_length=50, null=True, verbose_name='Album ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Song')),
                ('artist', models.CharField(blank=True, max_length=50, null=True, verbose_name='Artist')),
                ('album', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('txArtist', models.BooleanField(verbose_name='Texas artist?')),
            ],
        ),
        migrations.AddField(
            model_name='playlist',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shows.Show'),
        ),
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(blank=True, to='shows.Song', verbose_name='Songs'),
        ),
    ]
