# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-11 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shows', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='currentTrack',
            field=models.BooleanField(default=False, verbose_name='Current track?'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='deejay',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
